apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  labels:
    release: prom # Match the label of the Prometheus instance as per helm release
spec:
  selector:
    matchLabels:
      app: model
  namespaceSelector:
    matchNames:
      - default # or specific namespace
  endpoints:
    - port: '8000' # or match name of any other specific service port
      path: /metrics
      interval: 15s
